#!/bin/bash
set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)

RLY_HOME="$HOME/.yui-relayer"
RLY="${RLY_BIN} --debug"
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

if ! [ -x ${RLY_BIN} ]; then
  echo "Error: ${RLY_BIN} is not installed." >&2
  exit 1
fi

rm -rf ${RLY_HOME}

${RLY} config init
${RLY} chains add-dir configs/demo/

# setup key for tendermint client
SEED0=$(jq -r '.mnemonic' < ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json)
echo "Key $(${RLY} tendermint keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."
