/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Deposit } from "./Deposit";
export * as factories from "./factories";
export { Deposit__factory } from "./factories/Deposit__factory";
