#!/bin/bash

set -ux
CMD=$1

RLY_BIN=${RLY_BIN:-$(dirname $0)/../../../../../bin/yrly}
RLY="${RLY_BIN} --debug"
SHFU_DB=${SHFU_DB:-/tmp/shfu.db}

help() {
    test -z $1 || echo $1
    echo "$(basename $0) <start | stop | clean>"
}

clean() {
    for f in $SHFU_DB $SHFU_DB.pid $SHFU_DB-shm $SHFU_DB-wal; do
      test -f $f && rm $f
      echo "$f is cleaned"
    done
}

start() {
  if [ -f $SHFU_DB ]; then
    echo "$SHFU_DB already exists"
    exit 1
  fi

  set -e
  # to check metrics output
  # export YRLY_ENABLE_TELEMETRY=true
  # export OTEL_LOGS_EXPORTER=none
  # export OTEL_METRICS_EXPORTER=console
  # export OTEL_TRACES_EXPORTER=none

  $RLY lcp shfu dbinit --sqlite-path $SHFU_DB

  # make sure 1 record is registered
  $RLY lcp shfu update --sqlite-path $SHFU_DB ibc01:ibc0
  $RLY lcp shfu update --sqlite-path $SHFU_DB ibc01:ibc1
  test $($RLY lcp shfu dblist --sqlite-path $SHFU_DB --chain-id ibc0 --no-header | wc -l) -eq 1 || exit 1
  test $($RLY lcp shfu dblist --sqlite-path $SHFU_DB --chain-id ibc1 --no-header | wc -l) -eq 1 || exit 1

  $RLY lcp shfu server --grpc-addr localhost:50061 --sqlite-path $SHFU_DB --cleanup-age 30m ibc01:ibc0 ibc01:ibc1 &
  echo $! > $SHFU_DB.pid
  disown %1
}

stop() {
    test -f "${SHFU_DB}.pid" || { echo "PID file not found"; exit 1; }
    kill $(cat ${SHFU_DB}.pid)
}

case "x$CMD" in
  xclean)
      clean
      echo "cleaned"
      ;;
  xstart)
      start
      ;;
  xstop)
      stop
      ;;
  x)
      help "command required"
      ;;
  *)
      help "unknown command: $CMD"
      exit 1
      ;;
esac
