#!/bin/bash
set -eux

RLY="${RLY_BIN} --debug"

# XXX set proper value
TX_INTERNAL=120
TM_USER_ADDRESS=$(${RLY} tendermint keys show ibc0 testkey)

retry() {
    local -r -i max_attempts="$1"; shift
    local -r cmd="$@"
    local -i attempt_num=1

    until $cmd
    do
        if (( attempt_num == max_attempts ))
        then
            echo "Attempt $attempt_num failed and there are no more attempts left!"
            return 1
        else
            echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
            sleep $(( attempt_num++ ))
        fi
    done
}

echo "!!! ibc0 -> ibc1 !!!"

${RLY} tx transfer ibc01 ibc0 ibc1 100samoleans 0xa89f47c6b463f74d87572b058427da0a13ec5425
sleep 5
retry 10 ${RLY} tx relay ibc01
sleep ${TX_INTERNAL}
retry 10 ${RLY} tx acks ibc01
