ARG VERSION=latest
FROM chainsafe/lodestar:${VERSION}

# Install package of jq
RUN apt-get update && \
  apt-get install -y \
  bash jq curl coreutils && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/*

COPY ./scripts/lodestar_entrypoint.sh /lodestar_entrypoint.sh

ARG GETH_HTTP_PORT
ARG BEACON_HTTP_PORT
ENV GETH_HTTP_PORT=$GETH_HTTP_PORT
ENV BEACON_HTTP_PORT=$BEACON_HTTP_PORT

ENTRYPOINT ["bash", "/lodestar_entrypoint.sh"]
