ARG VERSION=latest
FROM ethereum/client-go:${VERSION}

# For health check
RUN apk add --no-cache bash curl jq sed

RUN mkdir -p /execution /config
COPY ./execution/genesis.json /execution/
COPY ./config /config

ENTRYPOINT ["bash", "/geth_entrypoint.sh"]
