#!/bin/bash
set -eux

DOCKER=docker
SCRIPT_DIR=$(cd $(dirname $0); pwd)
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

## Setup test fixtures

set +x
rm -rf ${FIXTURES_DIR}
mkdir -p ${FIXTURES_DIR}/xion/ibc0
mkdir -p ${FIXTURES_DIR}/xion/ibc1
set -x

## copy tendermint's node mnemonic from node container
${DOCKER} cp xion-chain0:/root/data/ibc0/key_seed.json  ${FIXTURES_DIR}/xion/ibc0/key_seed.json
${DOCKER} cp xion-chain1:/root/data/ibc1/key_seed.json  ${FIXTURES_DIR}/xion/ibc1/key_seed.json
${DOCKER} cp xion-chain0:/root/data/ibc0/validator_seed.json  ${FIXTURES_DIR}/xion/ibc0/validator_seed.json
${DOCKER} cp xion-chain1:/root/data/ibc1/validator_seed.json  ${FIXTURES_DIR}/xion/ibc1/validator_seed.json
