#!/bin/bash
set -eux

RLY="${RLY_BIN} --debug"

${RLY} lcp restore-elc ibc01 --src=false
#${RLY} lcp restore-elc ibc01 --src=true

${RLY} lcp remove-eki ibc01 --src=false
#${RLY} lcp remove-eki ibc01 --src=true
