name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-test:
    runs-on:
      labels: ubuntu-22.04
    env:
      SGX_MODE: SW
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: dtolnay/rust-toolchain@nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
        with:
          workspaces: |
            ./lcp
            ./enclave
          cache-directories: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
      - name: Install SGX SDK
        run: |
          sudo bash ./lcp/.github/scripts/install_sgx_sdk.sh /opt
      - name: Run E2E test
        run: |
          source /opt/sgxsdk/environment
          make prepare-contracts
          make build-images
          make E2E_OPTIONS="--upgrade_test --mock_zkdcap" e2e-test
